

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - testmdt-network
    restart: unless-stopped

  portregistration:
    build:
      context: ./Portregistration
      dockerfile: Dockerfile
    ports:
      - "81:81"
    depends_on:
      - backend
    networks:
      - testmdt-network
    restart: unless-stopped

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "10000-40000:10000:40000/udp"
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - testmdt-network
    restart: unless-stopped

  mysqldb:
    image: mysql:8.0  # Pinned version instead of 'latest'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=manage_port
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppassword
    volumes:
      - mysqldb-data:/var/lib/mysql
    ports:
      - "3306:3306"  # Exposed for debugging (remove in production)
    networks:
      - testmdt-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysqldb-data:

networks:
  testmdt-network:
    driver: bridge