services:
  config-server:
    image: "pyaephyol/config-server:v1.0.0"
    container_name: config-server
    ports:
      - "8071:8071"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8071/actuator/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: network-deploy-service

  eureka-server:
    image: "pyaephyol/eureka-server:v1.0.0"
    container_name: eureka-server
    ports:
      - "8070:8070"
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8070/actuator/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-configserver-config

  files-upload:
    image: "pyaephyol/files-upload:v1.0.0"
    container_name: files-upload
    ports:
      - "8000:8000"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/actuator/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

  clients:
    image: "pyaephyol/client-service:v1.0.0"
    container_name: client-service
    ports:
      - "8010:8010"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8010/actuator/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

  drones:
    image: "pyaephyol/drone-service:v1.0.0"
    container_name: drone-service
    ports:
      - "8020:8020"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8020/actuator/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

  materials:
    image: "pyaephyol/material-service:v1.0.0"
    container_name: material-service
    ports:
      - "8030:8030"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8030/actuator/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

  mechanic:
    image: "pyaephyol/mechanic-service:v1.0.0"
    container_name: mechanic-service
    ports:
      - "8040:8040"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8040/actuator/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

  gateway-server:
    image: "pyaephyol/gateway-server:v1.0.0"
    container_name: gateway-server
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      clients:
        condition: service_healthy
      files-upload:
        condition: service_healthy
      drones:
        condition: service_healthy
      materials:
        condition: service_healthy
      mechanic:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/actuator/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yaml
      service: microservice-eureka-config

  telemetry:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telemetry-service
    ports:
      - "8081:8081"
      - "3306:3306"
      - "14000-14050:14000-14050/udp"
      - "15000-15050:15000-15050/udp"
networks:
  aioceaneye:
    name: aioceaneye
    driver: bridge


