

services:
  mysql:
    image: mysql:8.0
    container_name: port_management_db
    environment:
      MYSQL_DATABASE: manage_port
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pilot_net

volumes:
  mysql_data:

networks:
  pilot_net: